### ISSUE TITLE
Deprecated function: PHP 8.1

### ISSUE THREAD

**Issue by bogomolov-dev** [rapidmail/rapidmail-apiv3-client-php#10]
Package version: 1.1.0
PHP version: 8.1

### Description:
> Deprecated function: Return type of Rapidmail\ApiClient\Service\Response\HalResponseResourceIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 10 of …/vendor/rapidmail/rapidmail-apiv3-client-php/src/Service/Response/HalResponseResourceIterator.php).

### Steps To Reproduce:
Create a new subscription under PHP 8.1.

```
      $this->apiClient->recipients()->create(
        $data,
        [
          'send_activationmail' => 'yes',
        ]
      );
```

**Comment by eth8505** [comment]
Thank you for reporting this. Please note that these are only deprecation notices, the code will still work with 8.1.
I have played around a little, the notices are gone on master as far as I can tell, however there seem to be some problems getting phpunit to run with coverage on 8.0 and 8.1 while the attributes are defined, so I can't create a new release as yet. It is proving more and more tricky to get a single code-base to run notice-free from 5.6 through 8.1 but I'm working on it.

**Comment by bogomolov-dev** [comment]
Thank you, @eth8505. Compatibility for 5.6 - 8.1 is really hard. But I can understand, if you need this "feature".
I am in the fortunate situation of always being able to work on the latest version.

**Comment by bnetz** [comment]
I really would appreciate a fix. I know that deprecation notices actually are no "danger", but suddenly when we switch to PHP 9 our system stops working and we have a lot of stress.

**Comment by eth8505** [comment]
@bnetz PHP9 doesn't even have a release date yet. Just a few weeks ago, PHP 8.2 was released and the next release will be PHP 8.3 to be released in november 2023 afaik. This basically means that 9.0 is at least 2 years out :)
I know deprecation warnings can be annoying, but they can easily be turned off via error_reporting(E_ALL ^ E_DEPRECATED);

**Comment by eth8505** [comment]
@bnetz i just released a new version of the API client that should silence the deprecation warnings.

**Comment by bnetz** [comment]
I installed it. Had to add manually the folder "vendor", because an include was missing in example-01-client-initialization.php
Now I get new deprecation warnings like:

`Deprecated: Return type of Rapidmail\ApiClient\Service\Response\HalResponsePaginationIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /my/path/src/Service/Response/HalResponsePaginationIterator.php on line 34`

**Comment by eth8505** [comment]
@bnetz please excuse the oversight, i also added the #ReturnTypeWillChange attribute to that iterator now and also fixed deprecation errors due to deprecated variable interpolation syntax. New release is out.

**Comment by bnetz** [comment]
Yes, this works, thanks a lot, @eth8505 !
