### ISSUE TITLE
Fatal error: During inheritance of ArrayAccess

### ISSUE THREAD

**Issue by FreddyFuchz** [rapidmail/rapidmail-apiv3-client-php#12]
## Description:
There is currently a compatibility error when using package version 1.1.0 with PHP 8.1. which results in a fatal error. 
Its possible to fix the issue by using the `dev-master` version of the package in my project.

### Package data:
 - Package version: 1.1.0
 - PHP version: 8.1.8
 
### Error:
`During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Rapidmail\ApiClient\Service\Response\HalResponse::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

**Comment by eth8505** [comment]
@FreddyFuchz it appears you're using a custom error handler that converts even PHP Notices to exceptions. This is a deprecation notice, warning you (and us) that we're using functionality that has been deprecated will be removed with PHP9. It does not affect the functionality of the API client.

**Comment by eth8505** [comment]
@FreddyFuchz published a new release that should silence the deprecation errors as recommended by the PHP docs.
