### ISSUE TITLE
creat new list got error 404:Exception raised: API error 404 when requesting https://apiv3.emailsys.net/v1/recipientlists. Detail: <html>

### ISSUE THREAD

**Issue by pedramham** [rapidmail/rapidmail-apiv3-client-php#13]
Hello 
For getting a list of emails from the recipientlists or adding an item to an existing list, everything works correctly.
```
        ///test get list recipient
        $listService = $client->recipientlists();

        foreach ($listService->query() as $list) {
            var_dump($list);
        }

        $recipientsService = $client->recipients();
        $recipientsService->create(
        // Dataset: Represents the recipient dataset you're creating
            [
                'recipientlist_id' => $list['id'], // Required
                'email' => 'td5474@thapke.de', // Required
                'firstname' => 'Test first name',
                'lastname' => 'Test last name',
                'gender' => 'male',
                'status' => "active"
            ],
        );
```

But when I try to use the recipientlists method to create a new list I got an error 

```
        $serviceCreate = $client->recipientlists();
        try {
        $response = $serviceCreate->create([
            [
                'name' => 'test', // Required
                'description' => 'test create list', 
                'unsubscribe_blacklist' => 'no',
                'recipient_subscribe_email' => 'no',
                'default' => 'no',
            ],
        ]);
            die($response);
        } catch (ApiClientException $e) {
            echo "Exception raised: " . $e->getMessage();

        }

```
I got error 404

```
Exception raised: API error 404 when requesting https://apiv3.emailsys.net/v1/recipientlists. Detail: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by eth8505** [comment]
Hello @pedramham.

I tried to reproduce this issue, but could not. Can you try to verify again if the issue persists? For me it works as expected with our test accounts and credentials. I saw that you already contacted our customer support directly. Please let them know which account you're working with so i can trace this further. Please do not post any account details or credentials here though :)

Best wishes
Jan

**Comment by pedramham** [comment]
Hello Simon. thank you for your rapid response.
is it possible it happened because *test_mode* is enabled in my account? if
it is how can I disable it?
----------------------------------------------
I have another question if there is a forum or group on slack or something like that that I can use please let me know.

Can I get only the data related to a list using the query method? I'm looking for something like this. 
with this query, I got all lists in the output

  $listService = $this->client->recipientlists();
        try {
            return $listService->query(['name' => 'listName']);
        } catch (ApiClientException $e) {
            // Catch API client exceptions
            echo "Exception raised: " . $e->getMessage();
        }

**Comment by eth8505** [comment]
@pedramham demo mode shouldn't affect your access to the API. This is especially awkward behavior as it seems to respond as HTML. The API should always return JSON responses though.
I may have found the cause though, found an exception from around the time you created your ticket concerning recipientlist creates via the API. Will look into it and get back to you.

Regarding your query question: Filtering lists by name is currently not supported.

**Comment by eth8505** [comment]
@pedramham we have identified the issue. It appears that under certain circumstances the API client generates an invalid request body. Working on a fix.

**Comment by eth8505** [comment]
@pedramham i just noticed where the actual issue lies, it's not the client afterall, you simply have an additional array level in your code:
```
$serviceCreate = $client->recipientlists();
        try {
        $response = $serviceCreate->create([
                'name' => 'test', // Required
                'description' => 'test create list', 
                'unsubscribe_blacklist' => 'no',
                'recipient_subscribe_email' => 'no',
                'default' => 'no',
        ]);
            die($response);
        } catch (ApiClientException $e) {
            echo "Exception raised: " . $e->getMessage();

        }
```

This is how your code should look - this will work.

I did however identify a bug on the server-side causing wrong responses if data like this is posted. Will be deploying a fix for it this morning.

**Comment by nielsnuebel** [comment]
@eth8505 did you use nginx or apache?  I have the same issues with nginx.
