### ISSUE TITLE
Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by eichie** [rapidmail/rapidmail-apiv3-client-php#16]
* Using ${var} in strings is deprecated, use {$var} instead
  vendor/rapidmail/rapidmail-apiv3-client-php/src/Util/PlatformRequirements.php:36

* Using ${var} in strings is deprecated, use {$var} instead
  vendor/rapidmail/rapidmail-apiv3-client-php/src/Util/PlatformRequirements.php:46

* Using ${var} in strings is deprecated, use {$var} instead
  vendor/rapidmail/rapidmail-apiv3-client-php/src/Service/ServiceFactory.php:57

* Using ${var} in strings is deprecated, use {$var} instead
  vendor/rapidmail/rapidmail-apiv3-client-php/src/Service/ServiceFactory.php:65

* Using ${var} in strings is deprecated, use {$var} instead
  vendor/rapidmail/rapidmail-apiv3-client-php/src/Service/ServiceFactory.php:78

**Comment by eth8505** [comment]
@eichie updated to use non-deprecated variable replacement syntax and tagged a new release with the fix. Thanks for reporting this.
