### ISSUE TITLE
HTTP/v1 is not supported by the cURL handler.

### ISSUE THREAD

**Issue by rkrx** [rapidmail/rapidmail-apiv3-client-php#21]
A version number that is probably not meant for Guzzle/cURL ([src](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/src/Service/ServiceFactory.php#L70)) passes through to cURL and throws an exception ([src](https://github.com/guzzle/guzzle/blob/7.9/src/Handler/CurlFactory.php#L57)).

Seems that each service has it's own version number. When the version number [here](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/src/Client.php#L139) is left blank, the version number will be taken from the [global config](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/src/Service/ServiceFactory.php#L60-L62). This version number is passed [here](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/src/Service/ServiceFactory.php#L86) to the createClient method of HttpClientFactory, which then passes it forward to Guzzle ([src](https://github.com/rapidmail/rapidmail-apiv3-client-php/blob/master/src/Http/HttpClientFactory.php#L43)). 

The version is `v1` in my case (as of `v1.1.6`).

**Comment by eth8505** [comment]
Thank you for bringing this to our attention, I will look into it this week.

**Comment by eth8505** [comment]
@rkrx I just merged your PR and released an updated version 1.1.7. Thank you for your work.
