### ISSUE TITLE
Outdated dependencies / project still maintained?

### ISSUE THREAD

**Issue by mnlmaier** [rapidmail/rapidmail-apiv3-client-php#7]
Hi,

I would like to use the Rapidmail API Client to connect Statamic (statamic.com) forms to Rapidmail. So far so good, still I think that some dependencies should be updated to keep compatibility high.

When trying to install the rapidmail api client via composer, the following error is coming up. Is this something which will be updated on your end in the future, or should i deal with it by forking the package? :)

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rapidmail/rapidmail-apiv3-client-php[1.0.0-beta, ..., 1.0.1] require guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires rapidmail/rapidmail-apiv3-client-php ^1.0 -> satisfiable by rapidmail/rapidmail-apiv3-client-php[1.0.0-beta, 1.0.0, 1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.```

**Comment by eth8505** [comment]
Hi @mnlmaier,

we do still maintain this of course, but sadly I can't give you any exact timeframe when we'll get around to this. If you need this resolved quickly I recommend forking the package for now.

**Comment by mnlmaier** [comment]
@eth8505 thanks, no worries – i'm glad to know that i can fully use this for a client project :) now that i think of it, for now it should be sufficient to use Laravel's HTTP wrapper since I only need to create a recipient without further actions. Once you got around to updating the package, I'll switch back to the official package.

Have a great start into 2021 and thanks for your work! :)

**Comment by eth8505** [comment]
@mnlmaier I just released an updated version including Guzzle7 support. Also comes with PHP8 support as an added bonus. Please feel free to check it out.
